{% set version = "3.3.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-tibble
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/tibble_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/tibble/tibble_{{ version }}.tar.gz
  sha256: 7f4c439f11b1aca4a45923d8d76f90fbab4e01acf0ba7ad0c38c3a7f22fee192

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - r-fansi >=0.4.0            # [build_platform != target_platform]
    - r-lifecycle >=1.0.0        # [build_platform != target_platform]
    - r-magrittr                 # [build_platform != target_platform]
    - r-pillar >=1.8.1           # [build_platform != target_platform]
    - r-pkgconfig                # [build_platform != target_platform]
    - r-rlang >=1.0.0            # [build_platform != target_platform]
    - r-vctrs >=0.4.2            # [build_platform != target_platform]
    - {{ compiler('c') }}        # [not win]
    - {{ stdlib("c") }}          # [not win]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ stdlib("m2w64_c") }}    # [win]
    - {{ posix }}filesystem      # [win]
    - {{ posix }}make
    - {{ posix }}sed             # [win]
    - {{ posix }}coreutils       # [win]
    - {{ posix }}zip             # [win]
  host:
    - r-base
    - r-fansi >=0.4.0
    - r-lifecycle >=1.0.0
    - r-magrittr
    - r-pillar >=1.8.1
    - r-pkgconfig
    - r-rlang >=1.0.2
    - r-vctrs >=0.4.2
  run:
    - r-base
    - r-fansi >=0.4.0
    - r-lifecycle >=1.0.0
    - r-magrittr
    - r-pillar >=1.8.1
    - r-pkgconfig
    - r-rlang >=1.0.2
    - r-vctrs >=0.4.2

test:
  commands:
    - $R -e "library('tibble')"           # [not win]
    - "\"%R%\" -e \"library('tibble')\""  # [win]

about:
  home: https://tibble.tidyverse.org/
  dev_url: https://github.com/tidyverse/tibble
  license: MIT
  summary: Provides a 'tbl_df' class (the 'tibble') that provides stricter checking and better formatting than the traditional data frame.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
