{% set version = "3.2.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-tibble
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/tibble_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/tibble/tibble_{{ version }}.tar.gz
  sha256: 65a72d0c557fd6e7c510d150c935ed6ced5db7d05fc20236b370f11428372131

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - r-ellipsis >=0.2.0         # [build_platform != target_platform]
    - r-fansi >=0.4.0            # [build_platform != target_platform]
    - r-lifecycle >=0.2.0        # [build_platform != target_platform]
    - r-magrittr                 # [build_platform != target_platform]
    - r-pillar >=1.5.0           # [build_platform != target_platform]
    - r-pkgconfig                # [build_platform != target_platform]
    - r-rlang >=0.4.3            # [build_platform != target_platform]
    - r-vctrs >=0.3.2            # [build_platform != target_platform]
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-ellipsis >=0.2.0
    - r-fansi >=0.4.0
    - r-lifecycle >=0.2.0
    - r-magrittr
    - r-pillar >=1.5.0
    - r-pkgconfig
    - r-rlang >=0.4.3
    - r-vctrs >=0.3.2
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-ellipsis >=0.2.0
    - r-fansi >=0.4.0
    - r-lifecycle >=0.2.0
    - r-magrittr
    - r-pillar >=1.5.0
    - r-pkgconfig
    - r-rlang >=0.4.3
    - r-vctrs >=0.3.2

test:
  commands:
    - $R -e "library('tibble')"           # [not win]
    - "\"%R%\" -e \"library('tibble')\""  # [win]

about:
  home: https://tibble.tidyverse.org/, https://github.com/tidyverse/tibble
  license: MIT
  summary: Provides a 'tbl_df' class (the 'tibble') that provides stricter checking and better formatting than the traditional data frame.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: tibble
# Title: Simple Data Frames
# Version: 3.0.0
# Authors@R: c(person(given = "Kirill", family = "M\u00fcller", role = c("aut", "cre"), email = "krlmlr+r@mailbox.org"), person(given = "Hadley", family = "Wickham", role = "aut", email = "hadley@rstudio.com"), person(given = "Romain", family = "Francois", role = "ctb", email = "romain@r-enthusiasts.com"), person(given = "Jennifer", family = "Bryan", role = "ctb", email = "jenny@rstudio.com"), person(given = "RStudio", role = "cph"))
# Description: Provides a 'tbl_df' class (the 'tibble') that provides stricter checking and better formatting than the traditional data frame.
# License: MIT + file LICENSE
# URL: https://tibble.tidyverse.org/, https://github.com/tidyverse/tibble
# BugReports: https://github.com/tidyverse/tibble/issues
# Depends: R (>= 3.1.0)
# Imports: cli, crayon (>= 1.3.4), ellipsis (>= 0.2.0), fansi (>= 0.4.0), lifecycle (>= 0.2.0), magrittr, methods, pillar (>= 1.4.3), pkgconfig, rlang (>= 0.4.3), utils, vctrs (>= 0.2.4)
# Suggests: bench, bit64, blob, covr, dplyr, evaluate, hms, htmltools, import, knitr, mockr, nycflights13, purrr, rmarkdown, testthat (>= 2.1.0), tidyr, withr
# VignetteBuilder: knitr
# RdMacros: lifecycle
# Encoding: UTF-8
# LazyData: yes
# RoxygenNote: 7.1.0
# NeedsCompilation: yes
# Packaged: 2020-03-29 13:30:48 UTC; kirill
# Author: Kirill Muller [aut, cre], Hadley Wickham [aut], Romain Francois [ctb], Jennifer Bryan [ctb], RStudio [cph]
# Maintainer: Kirill Muller <krlmlr+r@mailbox.org>
# Repository: CRAN
# Date/Publication: 2020-03-30 07:10:02 UTC
